/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiQuickCaptureRouteImport } from './routes/api/quick-capture'
import { Route as ApiDailyBriefRouteImport } from './routes/api/daily-brief'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as AppTareasRouteImport } from './routes/_app.tareas'
import { Route as AppReunionesRouteImport } from './routes/_app.reuniones'
import { Route as AppRecordatoriosRouteImport } from './routes/_app.recordatorios'
import { Route as AppNotasRouteImport } from './routes/_app.notas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatRouteImport } from './routes/_app.chat'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickCaptureRoute = ApiQuickCaptureRouteImport.update({
  id: '/api/quick-capture',
  path: '/api/quick-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyBriefRoute = ApiDailyBriefRouteImport.update({
  id: '/api/daily-brief',
  path: '/api/daily-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTareasRoute = AppTareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => AppRoute,
} as any)
const AppReunionesRoute = AppReunionesRouteImport.update({
  id: '/reuniones',
  path: '/reuniones',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordatoriosRoute = AppRecordatoriosRouteImport.update({
  id: '/recordatorios',
  path: '/recordatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppNotasRoute = AppNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/notas': typeof AppNotasRoute
  '/recordatorios': typeof AppRecordatoriosRoute
  '/reuniones': typeof AppReunionesRoute
  '/tareas': typeof AppTareasRoute
  '/api/ai': typeof ApiAiRoute
  '/api/daily-brief': typeof ApiDailyBriefRoute
  '/api/quick-capture': typeof ApiQuickCaptureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/notas': typeof AppNotasRoute
  '/recordatorios': typeof AppRecordatoriosRoute
  '/reuniones': typeof AppReunionesRoute
  '/tareas': typeof AppTareasRoute
  '/api/ai': typeof ApiAiRoute
  '/api/daily-brief': typeof ApiDailyBriefRoute
  '/api/quick-capture': typeof ApiQuickCaptureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notas': typeof AppNotasRoute
  '/_app/recordatorios': typeof AppRecordatoriosRoute
  '/_app/reuniones': typeof AppReunionesRoute
  '/_app/tareas': typeof AppTareasRoute
  '/api/ai': typeof ApiAiRoute
  '/api/daily-brief': typeof ApiDailyBriefRoute
  '/api/quick-capture': typeof ApiQuickCaptureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/chat'
    | '/dashboard'
    | '/notas'
    | '/recordatorios'
    | '/reuniones'
    | '/tareas'
    | '/api/ai'
    | '/api/daily-brief'
    | '/api/quick-capture'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/chat'
    | '/dashboard'
    | '/notas'
    | '/recordatorios'
    | '/reuniones'
    | '/tareas'
    | '/api/ai'
    | '/api/daily-brief'
    | '/api/quick-capture'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/notas'
    | '/_app/recordatorios'
    | '/_app/reuniones'
    | '/_app/tareas'
    | '/api/ai'
    | '/api/daily-brief'
    | '/api/quick-capture'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiDailyBriefRoute: typeof ApiDailyBriefRoute
  ApiQuickCaptureRoute: typeof ApiQuickCaptureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quick-capture': {
      id: '/api/quick-capture'
      path: '/api/quick-capture'
      fullPath: '/api/quick-capture'
      preLoaderRoute: typeof ApiQuickCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-brief': {
      id: '/api/daily-brief'
      path: '/api/daily-brief'
      fullPath: '/api/daily-brief'
      preLoaderRoute: typeof ApiDailyBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tareas': {
      id: '/_app/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof AppTareasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reuniones': {
      id: '/_app/reuniones'
      path: '/reuniones'
      fullPath: '/reuniones'
      preLoaderRoute: typeof AppReunionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recordatorios': {
      id: '/_app/recordatorios'
      path: '/recordatorios'
      fullPath: '/recordatorios'
      preLoaderRoute: typeof AppRecordatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notas': {
      id: '/_app/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AppNotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotasRoute: typeof AppNotasRoute
  AppRecordatoriosRoute: typeof AppRecordatoriosRoute
  AppReunionesRoute: typeof AppReunionesRoute
  AppTareasRoute: typeof AppTareasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotasRoute: AppNotasRoute,
  AppRecordatoriosRoute: AppRecordatoriosRoute,
  AppReunionesRoute: AppReunionesRoute,
  AppTareasRoute: AppTareasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAiRoute: ApiAiRoute,
  ApiDailyBriefRoute: ApiDailyBriefRoute,
  ApiQuickCaptureRoute: ApiQuickCaptureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
