/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiQuickCaptureRouteImport } from './routes/api/quick-capture'
import { Route as ApiDailyBriefRouteImport } from './routes/api/daily-brief'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRemindersRouteImport } from './routes/_app.reminders'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppNotesRouteImport } from './routes/_app.notes'
import { Route as AppMeetingsRouteImport } from './routes/_app.meetings'
import { Route as AppFinanzasRouteImport } from './routes/_app.finanzas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google.callback'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickCaptureRoute = ApiQuickCaptureRouteImport.update({
  id: '/api/quick-capture',
  path: '/api/quick-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyBriefRoute = ApiDailyBriefRouteImport.update({
  id: '/api/daily-brief',
  path: '/api/daily-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasRoute = AppFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/chat': typeof AppChatRoute
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/finanzas': typeof AppFinanzasRoute
  '/meetings': typeof AppMeetingsRoute
  '/notes': typeof AppNotesRoute
  '/projects': typeof AppProjectsRoute
  '/reminders': typeof AppRemindersRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/api/ai': typeof ApiAiRoute
  '/api/daily-brief': typeof ApiDailyBriefRoute
  '/api/quick-capture': typeof ApiQuickCaptureRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/chat': typeof AppChatRoute
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/finanzas': typeof AppFinanzasRoute
  '/meetings': typeof AppMeetingsRoute
  '/notes': typeof AppNotesRoute
  '/projects': typeof AppProjectsRoute
  '/reminders': typeof AppRemindersRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/api/ai': typeof ApiAiRoute
  '/api/daily-brief': typeof ApiDailyBriefRoute
  '/api/quick-capture': typeof ApiQuickCaptureRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finanzas': typeof AppFinanzasRoute
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/reminders': typeof AppRemindersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/api/ai': typeof ApiAiRoute
  '/api/daily-brief': typeof ApiDailyBriefRoute
  '/api/quick-capture': typeof ApiQuickCaptureRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/chat'
    | '/contacts'
    | '/dashboard'
    | '/finanzas'
    | '/meetings'
    | '/notes'
    | '/projects'
    | '/reminders'
    | '/settings'
    | '/tasks'
    | '/api/ai'
    | '/api/daily-brief'
    | '/api/quick-capture'
    | '/api/public/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/chat'
    | '/contacts'
    | '/dashboard'
    | '/finanzas'
    | '/meetings'
    | '/notes'
    | '/projects'
    | '/reminders'
    | '/settings'
    | '/tasks'
    | '/api/ai'
    | '/api/daily-brief'
    | '/api/quick-capture'
    | '/api/public/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/admin'
    | '/_app/chat'
    | '/_app/contacts'
    | '/_app/dashboard'
    | '/_app/finanzas'
    | '/_app/meetings'
    | '/_app/notes'
    | '/_app/projects'
    | '/_app/reminders'
    | '/_app/settings'
    | '/_app/tasks'
    | '/api/ai'
    | '/api/daily-brief'
    | '/api/quick-capture'
    | '/api/public/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiDailyBriefRoute: typeof ApiDailyBriefRoute
  ApiQuickCaptureRoute: typeof ApiQuickCaptureRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quick-capture': {
      id: '/api/quick-capture'
      path: '/api/quick-capture'
      fullPath: '/api/quick-capture'
      preLoaderRoute: typeof ApiQuickCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-brief': {
      id: '/api/daily-brief'
      path: '/api/daily-brief'
      fullPath: '/api/daily-brief'
      preLoaderRoute: typeof ApiDailyBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reminders': {
      id: '/_app/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finanzas': {
      id: '/_app/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof AppFinanzasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppChatRoute: typeof AppChatRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanzasRoute: typeof AppFinanzasRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppNotesRoute: typeof AppNotesRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppChatRoute: AppChatRoute,
  AppContactsRoute: AppContactsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanzasRoute: AppFinanzasRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppNotesRoute: AppNotesRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAiRoute: ApiAiRoute,
  ApiDailyBriefRoute: ApiDailyBriefRoute,
  ApiQuickCaptureRoute: ApiQuickCaptureRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
